<?php declare(strict_types=1);

namespace Expenses\Data;

use Atk4\Data\Model;

class Expense extends Model
{
    public $table = 'expense';
    public $caption = 'Ausgabe';

    protected function init(): void
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->addField(
            'date',
            ['type' => 'date', 'caption' => 'Datum']);
        $this->addField(
            'amount',
            ['type' => 'atk4_money', 'caption' => 'Betrag']);
        $this->addField(
            'description',
            ['type' => 'string', 'caption' => 'Beschreibung (optional)']
        );

        $this->hasOne(
            Category::class,
            [
                'model' => [Category::class],
                'actual' => 'category_id',
                'caption' => 'Kategorie'
            ]
        );

        $this->hasOne(
            User::class,
            [
                'model' => [Category::class],
                'actual' => 'user_id',
                'caption' => 'von Benutzer'
            ]
        );
    }
}