<?php declare(strict_types=1);

namespace Data;

use Atk4\Data\Model;
use Expenses\Data\Expense;
use PhilippR\Atk4\ModelTraits\CryptIdTrait;

class User extends Model
{
    use CryptIdTrait;

    public $table = 'user';
    public $caption = 'Benutzer';

    protected function init(): void
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->addField(
            'name',
            ['type' => 'string', 'caption' => 'Datum']);

        $this->addCryptIdFieldAndHooks('crypt_id');

        $this->hasMany(Expense::class, ['model' => [Expense::class]]);
    }

    public function generateCryptId(): string
    {
        $return = '';
        for ($i = 0; $i < 10; $i++) {
            $return .= $this->getRandomChar();
        }
        return $return;
    }
}